# Cloud Build configuration for deploying to Cloud Run
# This builds and deploys all services

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REGION: us-central1
  _REPOSITORY: proinspect

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Gateway Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-gateway'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway:latest'
      - '-f'
      - 'functions/gateway/Dockerfile'
      - '.'

  # Build Web Application
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-web'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web:latest'
      - '-f'
      - 'packages/web/Dockerfile'
      - 'packages/web'

  # Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web'

  # Deploy Gateway to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-gateway'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gateway'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3001'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,JWT_SECRET=jwt-secret:latest,SERVICE_SECRET=service-secret:latest'

  # Deploy Web Application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-web'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'web'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/gateway:latest'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/web:latest'

timeout: '1200s'