import 'dotenv/config';
export declare const config: {
    corsOrigins: string[];
    PACKAGE_VERSION: string;
    NODE_ENV: "test" | "development" | "production";
    PORT: number;
    HOST: string;
    LOG_LEVEL: string;
    LOG_PRETTY: boolean;
    RATE_LIMIT_MAX: number;
    RATE_LIMIT_WINDOW: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_ISSUER: string;
    JWT_AUDIENCE: string;
    API_BASE_URL: string;
    DATABASE_URL: string;
    JWT_JWKS_URL: string;
    SERVICE_AUTH_SECRET: string;
    MEDIA_SERVICE_URL: string;
    BILLING_SERVICE_URL: string;
    JOBS_SERVICE_URL: string;
    AUDIT_SERVICE_URL: string;
    REPORT_SERVICE_URL: string;
    CORS_ORIGIN?: string | undefined;
    REDIS_URL?: string | undefined;
    GIT_COMMIT?: string | undefined;
    BUILD_TIME?: string | undefined;
};
export type AppConfig = typeof config;
